name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: arc-runner-set
    container:
      image: containers.github.projectunity.io/mckain/granian-python314t:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Uv
        run: python3.14t -m pip install uv

      - name: Run tests
        env:
          DATABASE_HOST: postgres
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_NAME: postgres
        run: cd backend && uv run -- pytest .
